export type BlogBlock =
  | { type: 'heading'; text: string }
  | { type: 'paragraph'; text: string }
  | { type: 'image'; src: string }

export type BlogPost = {
  slug: string
  title: string
  date: string
  excerpt: string
  image: string
  category: string
  // Optional long-form fields (present once an article has been written).
  subtitle?: string
  author?: string
  authorRole?: string
  lead?: string
  content?: BlogBlock[]
}

export const blogPosts: BlogPost[] = [
  {
    slug: 'why-great-companies-stay-invisible',
    title: 'Why Great Companies Stay Invisible',
    date: 'May 2, 2025',
    excerpt: 'Most companies doing important work are completely invisible on LinkedIn. Here is why that happens and what to do about it.',
    image: '/images/8.png',
    category: 'Strategy',
    subtitle: "Some of the most important work in the world is being done by teams with almost no public presence. The challenge isn't innovation. It's visibility.",
    author: 'Cassidy Morris',
    authorRole: 'Founder',
    lead: 'Breakthrough technologies do not automatically find their audience. Explore why visibility has become essential infrastructure for bioscience, deep-tech, and innovation-driven companies.',
    content: [
      { type: 'paragraph', text: 'For most of modern business history, the best products did not always win.' },
      { type: 'paragraph', text: 'The best-known products did.' },
      { type: 'paragraph', text: 'Today, that dynamic has become even more pronounced.' },
      { type: 'paragraph', text: 'Every day, researchers are developing therapies that could change how we treat disease. Engineers are building technologies capable of transforming entire industries. Founders are solving problems that matter deeply to human health, climate resilience, and scientific progress.' },
      { type: 'paragraph', text: 'And yet many of these organizations remain largely invisible.' },
      { type: 'paragraph', text: 'Not because their work lacks value.' },
      { type: 'paragraph', text: 'Because visibility has become its own form of infrastructure.' },
      { type: 'paragraph', text: 'A breakthrough means very little if the people who can fund it, support it, adopt it, or amplify it never encounter it.' },
      { type: 'paragraph', text: 'This is one of the defining challenges facing bioscience and innovation-driven companies today.' },
      { type: 'image', src: '/images/11.png' },
      { type: 'heading', text: 'The Innovation Visibility Gap' },
      { type: 'paragraph', text: 'Spend enough time around research institutions, biotech startups, or deep-tech ventures and a pattern begins to emerge.' },
      { type: 'paragraph', text: 'Some of the most important work in the world is being done by teams with almost no public presence.' },
      { type: 'paragraph', text: 'A company may have spent years developing a breakthrough technology while maintaining a LinkedIn audience smaller than a local coffee shop.' },
      { type: 'paragraph', text: 'The science advances.' },
      { type: 'paragraph', text: 'The audience does not.' },
      { type: 'paragraph', text: 'The consequences are real.' },
      { type: 'paragraph', text: 'Potential investors never discover the company.' },
      { type: 'paragraph', text: 'Partnership opportunities fail to materialize.' },
      { type: 'paragraph', text: 'Researchers who could contribute never hear about the work.' },
      { type: 'paragraph', text: 'Talented candidates join more visible competitors.' },
      { type: 'paragraph', text: 'The challenge is not a lack of innovation.' },
      { type: 'paragraph', text: 'It is a lack of visibility.' },
      { type: 'heading', text: 'Why Visibility Matters More Than Ever' },
      { type: 'paragraph', text: 'LinkedIn has quietly become one of the most influential professional platforms in the world.' },
      { type: 'paragraph', text: 'Before meetings are booked, profiles are reviewed.' },
      { type: 'paragraph', text: 'Before partnerships are explored, company pages are visited.' },
      { type: 'paragraph', text: 'Before investment decisions progress, digital footprints are examined.' },
      { type: 'paragraph', text: 'People increasingly form opinions long before the first conversation takes place.' },
      { type: 'paragraph', text: 'In many cases, your LinkedIn presence becomes your first introduction.' },
      { type: 'paragraph', text: 'A silent page creates uncertainty.' },
      { type: 'paragraph', text: 'An active, thoughtful presence creates trust.' },
      { type: 'paragraph', text: 'This is not marketing in the traditional sense.' },
      { type: 'paragraph', text: 'It is reputation building.' },
      { type: 'heading', text: 'The Companies That Win Attention' },
      { type: 'paragraph', text: 'The organizations building meaningful audiences are rarely the loudest.' },
      { type: 'paragraph', text: 'They are the most consistent.' },
      { type: 'paragraph', text: 'They share insights from their work.' },
      { type: 'paragraph', text: 'They explain complex ideas clearly.' },
      { type: 'paragraph', text: 'They celebrate milestones.' },
      { type: 'paragraph', text: 'They highlight the people behind the science.' },
      { type: 'paragraph', text: 'Most importantly, they show up regularly.' },
      { type: 'paragraph', text: 'Over time, these signals compound.' },
      { type: 'paragraph', text: 'Visibility becomes familiarity.' },
      { type: 'paragraph', text: 'Familiarity becomes trust.' },
      { type: 'paragraph', text: 'Trust becomes opportunity.' },
      { type: 'heading', text: 'Building the Infrastructure' },
      { type: 'paragraph', text: 'Great companies should not have to choose between building important technology and communicating its value to the world.' },
      { type: 'paragraph', text: "But in today's environment, both matter." },
      { type: 'paragraph', text: 'The future will belong not only to the organizations creating extraordinary innovations, but also to those capable of helping others understand why those innovations matter.' },
      { type: 'paragraph', text: 'The challenge is no longer simply creating impact.' },
      { type: 'paragraph', text: 'It is making sure impact can be seen.' },
      { type: 'paragraph', text: 'Because the world cannot support what it never discovers.' },
      { type: 'image', src: '/images/15.png' },
      { type: 'heading', text: 'Final Thoughts' },
      { type: 'paragraph', text: 'Innovation changes the world only when the world can find it. In today\'s economy, visibility is not separate from impact. It is part of it.' },
    ],
  },
  {
    slug: 'invisible-variables-linkedin',
    title: 'The Invisible Variables Behind Every High-Performing LinkedIn Post',
    date: 'May 2, 2025',
    excerpt: 'Posting time, format, structure, and hook, the variables most companies ignore are the ones that determine reach.',
    image: '/images/20.png',
    category: 'Performance',
    subtitle: 'Content performance is no longer determined solely by what you publish. It is determined by the conditions surrounding it.',
    author: 'Cassidy Morris',
    authorRole: 'Founder',
    lead: 'Audience intent, time zones, engagement behavior, and algorithmic shifts all influence performance. Understanding these hidden variables is becoming essential for sustainable growth on LinkedIn.',
    content: [
      { type: 'paragraph', text: 'Most people think successful LinkedIn content comes down to good writing.' },
      { type: 'paragraph', text: 'A strong hook.' },
      { type: 'paragraph', text: 'A compelling story.' },
      { type: 'paragraph', text: 'A clear call to action.' },
      { type: 'paragraph', text: 'These things matter.' },
      { type: 'paragraph', text: 'But they are only part of the equation.' },
      { type: 'paragraph', text: 'Behind every high-performing LinkedIn post exists a network of invisible variables that most companies never see.' },
      { type: 'paragraph', text: 'The audience receiving the content.' },
      { type: 'paragraph', text: 'The time zone they live in.' },
      { type: 'paragraph', text: 'The format they engage with.' },
      { type: 'paragraph', text: 'The professional role they hold.' },
      { type: 'paragraph', text: 'The topics currently gaining traction within their industry.' },
      { type: 'paragraph', text: 'The signals the algorithm is rewarding this week, not last month.' },
      { type: 'paragraph', text: 'Content performance is no longer determined solely by what you publish.' },
      { type: 'paragraph', text: 'It is determined by the conditions surrounding it.' },
      { type: 'paragraph', text: 'And those conditions are constantly changing.' },
      { type: 'image', src: '/images/12.png' },
      { type: 'heading', text: 'The Myth of Universal Best Practices' },
      { type: 'paragraph', text: 'Spend ten minutes searching for LinkedIn advice and you will find hundreds of articles claiming to know the perfect formula.' },
      { type: 'paragraph', text: 'Post at 9am.' },
      { type: 'paragraph', text: 'Keep it under 1,300 characters.' },
      { type: 'paragraph', text: 'Use a carousel.' },
      { type: 'paragraph', text: 'Avoid links.' },
      { type: 'paragraph', text: 'Ask a question.' },
      { type: 'paragraph', text: 'The problem is that none of these recommendations are universally true.' },
      { type: 'paragraph', text: 'A post targeting biotech investors in Boston behaves differently than one targeting sustainability consultants in Zurich.' },
      { type: 'paragraph', text: 'A founder speaking to venture capitalists triggers different engagement patterns than a research institution speaking to scientists.' },
      { type: 'paragraph', text: 'Even identical content can perform dramatically differently depending on who sees it, when they see it, and what else is competing for their attention that day.' },
      { type: 'paragraph', text: 'The platform is dynamic.' },
      { type: 'paragraph', text: 'The audience is dynamic.' },
      { type: 'paragraph', text: 'The algorithm is dynamic.' },
      { type: 'paragraph', text: 'Why would the strategy remain static?' },
      { type: 'heading', text: 'LinkedIn Is an Adaptive System' },
      { type: 'paragraph', text: 'Every day, LinkedIn processes millions of interactions.' },
      { type: 'paragraph', text: 'It measures what people click.' },
      { type: 'paragraph', text: 'What they ignore.' },
      { type: 'paragraph', text: 'How long they read.' },
      { type: 'paragraph', text: 'Whether they comment.' },
      { type: 'paragraph', text: 'Whether they save.' },
      { type: 'paragraph', text: 'Whether they share.' },
      { type: 'paragraph', text: 'Whether they return.' },
      { type: 'paragraph', text: 'These signals continuously shape how content is distributed across the platform.' },
      { type: 'paragraph', text: 'The algorithm is constantly learning from user behavior.' },
      { type: 'paragraph', text: 'The challenge is that most companies are still operating from fixed assumptions.' },
      { type: 'paragraph', text: 'Strategies built six months ago.' },
      { type: 'paragraph', text: 'Content calendars created weeks in advance.' },
      { type: 'paragraph', text: 'Advice pulled from articles that may already be outdated.' },
      { type: 'paragraph', text: 'The result is predictable.' },
      { type: 'paragraph', text: 'Companies work harder.' },
      { type: 'paragraph', text: 'Results stagnate.' },
      { type: 'paragraph', text: 'Not because their content is poor.' },
      { type: 'paragraph', text: 'Because their strategy is disconnected from the environment it exists within.' },
      { type: 'heading', text: 'The Variables Most Companies Never Consider' },
      { type: 'paragraph', text: 'Every LinkedIn post enters a highly complex ecosystem.' },
      { type: 'paragraph', text: 'Audience intent matters.' },
      { type: 'paragraph', text: 'A founder researching investment opportunities behaves differently than a scientist exploring new research.' },
      { type: 'paragraph', text: 'Time zone matters.' },
      { type: 'paragraph', text: 'A post published at the optimal time for London may miss its audience entirely in California.' },
      { type: 'paragraph', text: 'Industry matters.' },
      { type: 'paragraph', text: 'The engagement patterns of bioscience professionals differ significantly from those of technology founders, consultants, or policymakers.' },
      { type: 'paragraph', text: 'Content format matters.' },
      { type: 'paragraph', text: 'Different audiences respond differently to text posts, carousels, documents, videos, and visual storytelling.' },
      { type: 'paragraph', text: 'Engagement quality matters.' },
      { type: 'paragraph', text: 'The algorithm increasingly prioritizes signals such as saves, dwell time, meaningful comments, and content sharing over passive reactions.' },
      { type: 'paragraph', text: 'None of these variables operate independently.' },
      { type: 'paragraph', text: 'They interact continuously.' },
      { type: 'paragraph', text: 'Which means optimization is not a one-time activity.' },
      { type: 'paragraph', text: 'It is an ongoing process.' },
      { type: 'heading', text: 'Why Human-Led Optimization Has Limits' },
      { type: 'paragraph', text: 'The reality is simple.' },
      { type: 'paragraph', text: 'No individual marketer can continuously track thousands of evolving signals across industries, audiences, formats, engagement patterns, and algorithmic changes.' },
      { type: 'paragraph', text: 'The amount of information influencing content performance has become too large.' },
      { type: 'paragraph', text: 'Human intuition remains valuable.' },
      { type: 'paragraph', text: 'But intuition alone is no longer enough.' },
      { type: 'paragraph', text: 'The companies seeing the strongest results are increasingly supported by systems capable of processing far more information than any person can reasonably manage.' },
      { type: 'paragraph', text: 'Not replacing human creativity.' },
      { type: 'paragraph', text: 'Enhancing it.' },
      { type: 'paragraph', text: 'Providing the intelligence layer that allows creativity to reach the right audience at the right time.' },
      { type: 'heading', text: 'A Different Approach' },
      { type: 'paragraph', text: 'This is the challenge Linkwright was built to solve.' },
      { type: 'paragraph', text: 'Rather than relying on fixed templates or generic best practices, our system continuously analyzes evolving platform behavior and audience dynamics.' },
      { type: 'paragraph', text: 'Who the audience is.' },
      { type: 'paragraph', text: 'Where they are located.' },
      { type: 'paragraph', text: 'When they are active.' },
      { type: 'paragraph', text: 'What content formats are performing.' },
      { type: 'paragraph', text: 'How engagement patterns are shifting.' },
      { type: 'paragraph', text: 'Which signals the algorithm is rewarding.' },
      { type: 'paragraph', text: 'The system adapts as those variables change.' },
      { type: 'paragraph', text: 'Because LinkedIn is not static.' },
      { type: 'paragraph', text: 'A strategy that works today may not be the strategy that works next month.' },
      { type: 'paragraph', text: 'Effective communication on the platform increasingly requires continuous adaptation.' },
      { type: 'paragraph', text: 'Not periodic adjustment.' },
      { type: 'paragraph', text: 'Continuous adaptation.' },
      { type: 'heading', text: 'The Future of LinkedIn Strategy' },
      { type: 'paragraph', text: 'For years, companies treated LinkedIn as a publishing platform.' },
      { type: 'paragraph', text: 'Increasingly, it behaves more like a living ecosystem.' },
      { type: 'paragraph', text: 'The organizations that succeed will not necessarily be the ones creating more content.' },
      { type: 'paragraph', text: 'They will be the ones creating more informed content.' },
      { type: 'paragraph', text: 'Content built around real-time audience behavior.' },
      { type: 'paragraph', text: 'Content calibrated to changing algorithmic conditions.' },
      { type: 'paragraph', text: 'Content supported by systems capable of learning as quickly as the platform itself.' },
      { type: 'paragraph', text: 'Because in an environment that changes every day, the greatest competitive advantage is not simply having a voice.' },
      { type: 'paragraph', text: 'It is knowing how to make sure the right people hear it.' },
      { type: 'image', src: '/images/16.png' },
      { type: 'heading', text: 'Final Thoughts' },
      { type: 'paragraph', text: 'Success on LinkedIn is no longer about posting more. It is about understanding the complex system your content enters the moment you hit publish.' },
    ],
  },
  {
    slug: 'most-valuable-metric-linkedin',
    title: 'The Most Valuable Metric on LinkedIn Isn\'t Likes. It\'s Saves.',
    date: 'May 2, 2025',
    excerpt: 'Saves signal that someone found your content worth returning to. That is the audience you actually want to build.',
    image: '/images/17.png',
    category: 'Analytics',
    subtitle: 'Likes signal approval. Saves signal value. The algorithm knows the difference.',
    author: 'Cassidy Morris',
    authorRole: 'Founder',
    lead: 'Most companies optimize for vanity metrics. The organizations building lasting audiences understand that the strongest engagement signal is often the one nobody is measuring.',
    content: [
      { type: 'paragraph', text: 'Most companies are measuring the wrong things on LinkedIn.' },
      { type: 'paragraph', text: 'They watch impressions.' },
      { type: 'paragraph', text: 'They celebrate likes.' },
      { type: 'paragraph', text: 'They report follower growth.' },
      { type: 'paragraph', text: 'Meanwhile, one of the most important signals on the platform receives almost no attention at all.' },
      { type: 'paragraph', text: 'Saves.' },
      { type: 'paragraph', text: 'A save happens when someone encounters a piece of content and decides it is valuable enough to revisit later.' },
      { type: 'paragraph', text: 'It is one of the strongest signals of relevance a user can send.' },
      { type: 'paragraph', text: 'And increasingly, it is one of the strongest signals the LinkedIn algorithm can receive.' },
      { type: 'image', src: '/images/9.png' },
      { type: 'heading', text: 'The Difference Between Attention and Value' },
      { type: 'paragraph', text: 'A like requires almost no commitment.' },
      { type: 'paragraph', text: 'A save is different.' },
      { type: 'paragraph', text: 'A save suggests that someone found the content useful enough to keep.' },
      { type: 'paragraph', text: 'Perhaps it contained an industry insight they wanted to reference.' },
      { type: 'paragraph', text: 'A framework worth sharing with a colleague.' },
      { type: 'paragraph', text: 'Data they planned to revisit.' },
      { type: 'paragraph', text: 'A perspective they did not want to lose.' },
      { type: 'paragraph', text: 'The distinction matters.' },
      { type: 'paragraph', text: 'Likes indicate approval.' },
      { type: 'paragraph', text: 'Saves indicate value.' },
      { type: 'paragraph', text: 'The algorithm understands this difference.' },
      { type: 'heading', text: 'Why Saves Matter' },
      { type: 'paragraph', text: 'Modern social platforms are designed to maximize user retention.' },
      { type: 'paragraph', text: 'The content they reward most heavily is content that keeps people engaged with the platform over time.' },
      { type: 'paragraph', text: 'When a user saves a post, they are signaling that the content has ongoing utility.' },
      { type: 'paragraph', text: 'In algorithmic terms, that makes it exceptionally valuable.' },
      { type: 'paragraph', text: 'A post that earns meaningful saves is often interpreted as content worth distributing further because it has demonstrated lasting relevance rather than fleeting attention.' },
      { type: 'paragraph', text: 'The best content is not simply consumed.' },
      { type: 'paragraph', text: 'It becomes a resource.' },
      { type: 'heading', text: 'Creating Content People Save' },
      { type: 'paragraph', text: 'Most companies unintentionally optimize for reactions.' },
      { type: 'paragraph', text: 'The companies building durable audiences optimize for utility.' },
      { type: 'paragraph', text: 'They publish original research, industry frameworks, practical insights, data-driven observations, and lessons learned through experience.' },
      { type: 'paragraph', text: 'Content that solves problems tends to generate saves.' },
      { type: 'paragraph', text: 'Content designed only to entertain rarely does.' },
      { type: 'heading', text: 'The Long-Term Advantage' },
      { type: 'paragraph', text: 'This is where many LinkedIn strategies fail.' },
      { type: 'paragraph', text: 'They chase short-term engagement instead of long-term value.' },
      { type: 'paragraph', text: 'But audience growth is rarely the result of a single viral post.' },
      { type: 'paragraph', text: 'It is the outcome of repeatedly publishing content that people return to.' },
      { type: 'paragraph', text: 'A saved post continues creating value long after publication.' },
      { type: 'paragraph', text: 'It gets revisited, shared internally, referenced later, and recommended to others.' },
      { type: 'paragraph', text: 'Its lifespan extends far beyond the initial engagement window.' },
      { type: 'heading', text: 'Building for Reference Value' },
      { type: 'paragraph', text: 'The strongest LinkedIn content today is not optimized for attention.' },
      { type: 'paragraph', text: 'It is optimized for usefulness.' },
      { type: 'paragraph', text: 'The goal is not simply to stop the scroll.' },
      { type: 'paragraph', text: 'The goal is to create something worth returning to.' },
      { type: 'paragraph', text: 'When companies begin thinking this way, their content changes.' },
      { type: 'paragraph', text: 'And when their content changes, their audience does too.' },
      { type: 'paragraph', text: 'Because the posts people save are often the posts they remember.' },
      { type: 'paragraph', text: 'And the companies they remember are the companies they trust.' },
      { type: 'image', src: '/images/7.png' },
      { type: 'heading', text: 'Final Thoughts' },
      { type: 'paragraph', text: 'The best LinkedIn content is not designed to be consumed once. It is designed to become a resource people return to again and again.' },
    ],
  },
  {
    slug: 'linkedin-advice-outdated',
    title: 'Why Most LinkedIn Advice Is Outdated Before It\'s Published',
    date: 'May 2, 2025',
    excerpt: 'The LinkedIn algorithm changes constantly. Content strategies built on last year\'s data are working against you.',
    image: '/images/4.png',
    category: 'Strategy',
  },
]
