export const companies = [
  {
    id: "cpolar",
    name: "C-POLAR Technologies",
    tagline: "Ambient Protection™ for modern life.",
    color: "#91BC07",
    colorDark: "#2B2B2B",
    colorLight: "#F0F0F0",
    colorBorder: "#91BC07",
    colorText: "#2B2B2B",
    brand: {
      palette: ["#91BC07","#2B2B2B","#F0F0F0","#DCD8CF","#837F7A","#FFFFFF"],
      style: "quiet-premium",
      visualMood: "Soft neutral stone and grey backgrounds. Full-bleed lifestyle photography (homes, nature, people breathing). Bold white or near-black headline text. Lime green #91BC07 used on 2-3 key words only — never as background. Clean, quiet, never alarming. The brand principle: the most effective protection works quietly. Our visual system does the same.",
      logoText: "C-POLAR™",
      accentColor: "#91BC07",
      darkColor: "#2B2B2B",
      lightColor: "#F0F0F0",
      warmColor: "#DCD8CF",
      keyPhrases: ["Ambient Protection™","NanoFlashing™","Built in. Always on.","Protection should not depend on behavior.","The environments around us shape our health."],
    },
    timezone: "EST",
    timezoneNote: "North American enterprise & facility management — Eastern US is the largest procurement market",
    bestPostTimes: {
      Tuesday:   "9:00 AM EST",
      Wednesday: "10:00 AM EST",
      Thursday:  "9:00 AM EST",
      Friday:    "3:00 PM EST",
    },
    scheduleRationale: {
      Tuesday:   "Facility managers arrive 8–9 AM — catch them at desk once settled. Awareness content fits mid-morning routine check.",
      Wednesday: "Peak B2B day. 10 AM hits enterprise buyers after their morning standup. Thought leadership window before lunch.",
      Thursday:  "Operations teams review vendor/product content Thu morning. Proof posts land well before end-of-week decisions.",
      Friday:    "3 PM Friday = facilities planning for the coming week. Softer engagement but high intent from ops leaders.",
    },
    audienceRegion: "U.S. East Coast — enterprise facilities, public health agencies, hospital networks",
    scheduleStrategy: "EST morning/mid-morning for enterprise ops. Friday afternoon for end-of-week planning mindset.",
    audience: "Facility managers, public health officials, enterprise buyers, health-conscious consumers, investors",
    voice: "Quietly confident. We never shout, never scare, never overexplain. Warm but precise — human, never clinical. Smart, never cold. Elevated, not trendy. Reassuring, not alarmist. We talk about better living, not threats. State facts simply and let them stand. Our audience is discerning, curious, and values quality.",
    badges: ["Ambient Protection™","NanoFlashing™","Air filtration","Water","Medical devices","PPE","ReinFire™","Inhalo™"],
    pillars: [
      { day: "Tuesday", type: "Science insight", color: "#91BC07", example: "How NanoFlashing™ creates a permanent positive electrostatic charge that eliminates bacteria, viruses, and fungi on contact — no chemicals, no electricity, no maintenance." },
      { day: "Wednesday", type: "Human story", color: "#837F7A", example: "The BGIS senior director who ran C-POLAR for 3 months: what the data showed, what changed, what surprised him." },
      { day: "Thursday", type: "Industry POV", color: "#2B2B2B", example: "We spend 90% of our lives indoors. Protection that depends on behavior, compliance, or vigilance will always fail. It's time to build it in." },
      { day: "Friday", type: "Proof & traction", color: "#91BC07", example: "Harvard's Dr. Michael Mansour: C-POLAR is 'an essential interrupter of infectious spread.' What peer-reviewed independent validation means for scale." },
    ],
    postingDays: ["Tuesday","Wednesday","Thursday","Friday"],
  },
  {
    id: "oxia",
    name: "Oxia Therapeutics",
    tagline: "The end of irreversible damage.",
    color: "#2BBFB0",
    colorDark: "#1A3D4F",
    colorLight: "#F5F2EE",
    colorBorder: "#2BBFB0",
    colorText: "#1A3D4F",
    brand: {
      palette: ["#2BBFB0","#1A3D4F","#E8504A","#F5F2EE","#FFFFFF","#2A6B7C"],
      style: "elegant-scientific",
      visualMood: "Two modes: (1) Dark teal-to-navy backgrounds with wide-tracked spaced caps headlines in white, coral/salmon #E8504A on 2-3 power words. (2) Clean warm off-white #F5F2EE backgrounds with dark navy #1A3D4F headers and teal #2BBFB0 on accent words. Teal glass molecular imagery. Never loud — always refined. Key design feel: scientific confidence meets human warmth.",
      logoText: "OXIA",
      accentColor: "#2BBFB0",
      darkColor: "#1A3D4F",
      lightColor: "#F5F2EE",
      coralAccent: "#E8504A",
      keyPhrases: ["The end of irreversible damage.","We don't need to replace biology. We need to turn it back on.","Aging isn't programmed. It's what happens when repair fails.","Not managing decline. Reversing it.","The body knows how to repair. Over time, it just stops."],
    },
    timezone: "EST",
    timezoneNote: "Boston/Cambridge is the #1 biotech hub — catches NYC & SF investors at mid-morning on the West Coast",
    bestPostTimes: {
      Tuesday:   "8:15 AM EST",
      Wednesday: "9:00 AM EST",
      Thursday:  "9:30 AM EST",
      Friday:    "9:00 AM EST",
    },
    scheduleRationale: {
      Tuesday:   "Researchers and clinicians check LinkedIn before lab/rounds. 8:15 AM EST catches Boston/NYC biotech community at start of day.",
      Wednesday: "9 AM EST is peak for biotech investors and research directors. Thought leadership on the strongest engagement day of the week.",
      Thursday:  "Mid-morning Thu hits scientific professionals doing weekly literature/industry review. Proof data lands with high credibility.",
      Friday:    "9 AM EST = end-of-week reflection mode. Regenerative medicine content performs well as researchers wind down toward weekend reading.",
    },
    audienceRegion: "U.S. East Coast — Boston/Cambridge biotech corridor, NYC investors, academic medical centers",
    scheduleStrategy: "EST early morning on Tue/Fri for researcher audience. EST mid-morning Wed/Thu for investor and clinical decision-makers.",
    audience: "Biotech investors, regenerative medicine researchers, clinicians, cardiovascular/renal specialists, healthcare systems",
    voice: "Visionary yet precise. Blends profound hope with hard preclinical data. References 30 years of Baylor science as credibility anchor. Never hypes — always grounds bold claims in evidence. Speaks to what medicine has been missing for decades. Tone: the quiet confidence of people who have the data and know what it means.",
    badges: ["ERM Therapies™","SRC biology","Cellular repair","Stroke","Kidney injury","Myocardial infarction","Gorlin Immuno-Longevity","$75M raise"],
    pillars: [
      { day: "Tuesday", type: "Science insight", color: "#2BBFB0", example: "What are Steroid Receptor Coactivators? The master regulators of cellular repair that Oxia's ERM platform activates — and why targeting the control point changes everything." },
      { day: "Wednesday", type: "Human story", color: "#1A3D4F", example: "Inside Dr. Lisa McClendon's lab at Baylor: what a day of cellular repair discovery actually looks like, and the moment the data changed everything." },
      { day: "Thursday", type: "Industry POV", color: "#2BBFB0", example: "We extended lifespan for 100 years. Now we've hit a ceiling. Medicine got better at keeping people alive. It didn't get better at keeping them well." },
      { day: "Friday", type: "Proof & data", color: "#E8504A", example: "78% reduction in fibrosis. Preserved organ function. Blood vessel regeneration. Cells survive at 1% oxygen. The preclinical data that changes what we thought possible." },
    ],
    postingDays: ["Tuesday","Wednesday","Thursday","Friday"],
  },
  {
    id: "coregen",
    name: "CoRegen",
    tagline: "The future of cancer eradication therapy.",
    color: "#E8181A",
    colorDark: "#0D0D1A",
    colorLight: "#F5F5F7",
    colorBorder: "#E8181A",
    colorText: "#0D0D1A",
    brand: {
      palette: ["#E8181A","#0D0D1A","#1A1A3E","#FFFFFF","#F5F5F7","#2A2A4A"],
      style: "dark-cinematic-bold",
      visualMood: "Near-black #0D0D1A and deep navy #1A1A3E backgrounds dominate. Full-bleed cinematic photography: DNA double helices, cancer cell targeting crosshairs, blood cell microscopy. White bold condensed sans-serif headlines at large scale. Red #E8181A used exclusively on the 2-3 most important words in any headline — never as background. Historic and urgent. The tone of a company that knows it has something the world has been waiting for.",
      logoText: "CoRegen",
      accentColor: "#E8181A",
      darkColor: "#0D0D1A",
      lightColor: "#F5F5F7",
      navyColor: "#1A1A3E",
      keyPhrases: ["The future of cancer eradication therapy.","We can change this.","CoRegen's technology has the potential to make cancer obsolete.","Groundbreaking. Disruptive. Scalable. Accessible.","This is the breakthrough the whole world has been waiting for."],
    },
    timezone: "EST",
    timezoneNote: "Key oncology hubs: Dana-Farber (Boston), MSK (NYC), MD Anderson (Houston) — EST captures all three at peak attention",
    bestPostTimes: {
      Tuesday:   "8:00 AM EST",
      Wednesday: "8:30 AM EST",
      Thursday:  "10:00 AM EST",
      Friday:    "12:00 PM EST",
    },
    scheduleRationale: {
      Tuesday:   "8 AM EST = oncology researchers and lab teams starting their day. First-mover advantage on awareness content before the feed fills up.",
      Wednesday: "8:30 AM EST is the prime thought leadership window. Biotech investors and oncology community are most active Wed morning — CoRegen's strongest content slot.",
      Thursday:  "10 AM EST catches investors after their morning meetings. Proof and clinical data posts get highest credibility read on Thu mid-morning.",
      Friday:    "12 PM EST Friday lunch = cancer research community's reflective window. Historic narrative and human story content resonates strongly.",
    },
    audienceRegion: "U.S. East Coast — Dana-Farber, MSK, MD Anderson, NIH, major cancer research institutions and biotech investors",
    scheduleStrategy: "EST early-morning priority on Tue/Wed to lead the feed. Thu mid-morning for data credibility. Fri lunch for narrative and community.",
    audience: "Oncology researchers, immuno-oncology community, biotech investors, cancer patient advocates, pharma partners",
    voice: "Urgent and historic. Speaks with the full confidence of nearly 50 years of foundational science. References the Cozzarelli Prize, PNAS publication, Baylor College of Medicine, Dr. Bert O'Malley. Backs every bold claim with data — complete tumour eradication in 400+ mice, 7 cancer types, zero recurrence, zero toxicity. Never tentative. The tone of a company that knows exactly what it has.",
    badges: ["SRC-3 KO Tregs","CRG-150","Glioblastoma","TNBC","Pancreatic","Prostate","No toxicity","PNAS Cozzarelli Prize 2023","Baylor College of Medicine","Phase 1 2026"],
    pillars: [
      { day: "Tuesday", type: "Science insight", color: "#E8181A", example: "1 gene. Out of 22,000. In 1 cell type. Out of 200. That's what CoRegen identified. Knock out SRC-3 in Treg cells and cancer loses its ability to hide from the immune system — permanently." },
      { day: "Wednesday", type: "Human story", color: "#2A2A4A", example: "Nearly 50 years of molecular research. Dr. Bert O'Malley's journey from discovering how hormones work to the science that may eradicate cancer." },
      { day: "Thursday", type: "Industry POV", color: "#E8181A", example: "Every major cancer therapy for 50 years has been toxic. The side effects are considered acceptable because there was no alternative. CoRegen is the alternative." },
      { day: "Friday", type: "Proof & science", color: "#E8181A", example: "Complete tumour eradication. No recurrence. No toxicity. 7 cancer types. 400+ mice. Published in PNAS. Winner of the 2023 Cozzarelli Prize. This is what the data shows." },
    ],
    postingDays: ["Tuesday","Wednesday","Thursday","Friday"],
  },
  {
    id: "intrepro",
    name: "IntrePro + Klim-Loc",
    tagline: "The smart medtech company. Built to eliminate the needle.",
    color: "#2BBFB0",
    colorDark: "#1A3A38",
    colorLight: "#EAF8F7",
    colorBorder: "#2BBFB0",
    colorText: "#1A3A38",
    brand: {
      palette: ["#2BBFB0","#1A3A38","#FFFFFF","#EAF8F7","#2A5A55","#00A896"],
      style: "clean-medtech-teal",
      visualMood: "Dark teal #1A3A38 to near-black gradient backgrounds on hero slides. Clean white backgrounds on data/product slides. Teal #2BBFB0 as dominant accent on key words, the 'O' in Klim-LOC logo, borders and icons. Clinical but accessible photography: gloved hands, vials, hospital corridors, flight paramedics. Bold white sans-serif on dark. The brand projects competence and innovation simultaneously.",
      logoText: "KLIM-LOC",
      accentColor: "#2BBFB0",
      darkColor: "#1A3A38",
      lightColor: "#EAF8F7",
      keyPhrases: ["The smart medtech company.","Needles are simply outdated, unsafe, and unnecessary for most applications.","Same old thing with little to no innovation... until now.","Redesign the pharmaceutical vial cap.","$1 billion in annual needlestick injury costs. We're solving it."],
    },
    timezone: "EST",
    timezoneNote: "Hospital procurement & DoD concentrated in Northeast/DC corridor — EST is the primary decision-maker timezone",
    bestPostTimes: {
      Monday:    "8:30 AM EST",
      Wednesday: "12:00 PM EST",
      Friday:    "8:00 AM EST",
      Saturday:  "10:00 AM EST",
    },
    scheduleRationale: {
      Monday:    "Hospital procurement teams start planning cycles Monday morning. 8:30 AM EST catches them at their first desk review of the week.",
      Wednesday: "12 PM EST Wednesday = lunch break for infection control and pharma manufacturing professionals. Highest dwell time for technical content mid-week.",
      Friday:    "8 AM EST Friday = procurement managers doing end-of-week vendor review. Early post captures attention before the day winds down.",
      Saturday:  "10 AM EST Saturday reaches DoD/military medics and ICU nurses who browse LinkedIn on weekends. Smaller audience but high intent.",
    },
    audienceRegion: "U.S. East Coast — Northeast hospital systems, DC/Pentagon DoD, pharma fill-and-finish facilities (NJ/PA corridor)",
    scheduleStrategy: "EST with Mon/Fri early morning for procurement ops mindset. Wed lunch for max dwell time on technical content. Sat for DoD/clinical niche.",
    audience: "Hospital procurement, infection control professionals, pharma manufacturing (fill & finish), DoD/military medicine, med-device investors, Baxter/Gerresheimer/Medline partners",
    voice: "Precise and credible. Clinical in tone but genuinely accessible. 'The smart medtech company.' Bridges materials science and patient safety without oversimplifying. The Klim-Loc/IntrePro story is a powerful content asset — a flight paramedic who spent 20 years watching needles cause harm and built a patented solution. Pragmatic, problem-solver energy. Never academic.",
    badges: ["Needleless vial cap","3 patents filed","Antimicrobial polymer","Sensor technology","Pharmapack Europe 2024 award","DoD / BARDA consortia","Baxter interest","Product launch 2026","C-POLAR spinout"],
    pillars: [
      { day: "Monday", type: "Science insight", color: "#2BBFB0", example: "A single vial cap redesign eliminates the needle from the medication workflow entirely — and with it, the contamination risk, the sharps waste, and the injury cost. Here's how." },
      { day: "Wednesday", type: "Human story", color: "#1A3A38", example: "Robbie Klimek: 20 years as a certified flight paramedic. One problem he watched injure colleagues every day. One patented solution that's now heading to market in 2026." },
      { day: "Friday", type: "Industry POV", color: "#2BBFB0", example: "Needlestick injuries cost US healthcare $1 billion annually. 385,000 healthcare workers are injured every year. The needle is the problem. We built the replacement." },
      { day: "Saturday", type: "Proof & pipeline", color: "#1A3A38", example: "Pharmapack Europe 2024 award. DoD consortia. Baxter, Gerresheimer, Medline interest. Three patents. Working prototype. Klim-Loc launches in 2026. Here's where we stand." },
    ],
    postingDays: ["Monday","Wednesday","Friday","Saturday"],
  },
  {
    id: "senvi",
    name: "Senvi",
    tagline: "Removing what aging leaves behind.",
    color: "#2BBFB3",
    colorDark: "#0A2A28",
    colorLight: "#E0F9F7",
    colorBorder: "#2BBFB3",
    colorText: "#0A2A28",
    brand: {
      palette: ["#2BBFB3","#0A2A28","#FFFFFF","#E0F9F7","#1A8A84","#000D0C"],
      style: "teal-cinematic-scientific",
      visualMood: "Two modes: (1) Dark near-black #0A2A28 to teal #2BBFB3 gradient backgrounds — huge display type, white headlines, teal on key scientific words. Used for concept/mission slides. (2) Clean white backgrounds — teal #2BBFB3 headlines for science slides, black body copy. Molecular structure imagery floating in space. Cellular microscopy in teal tones. The infinity mark is the visual anchor. Always elegant — sits between a Nature paper and a TED talk.",
      logoText: "senvi",
      accentColor: "#2BBFB3",
      darkColor: "#0A2A28",
      lightColor: "#E0F9F7",
      keyPhrases: ["Removing what aging leaves behind.","Making ineffective treatments effective.","What are senescent cells? The cells that stop dividing but don't die — and slowly poison everything around them.","SenC eliminates senescent cells. In 7 days.","Complete tumour elimination in combination. 70% senescent signal reduction. >98% topical clearance."],
    },
    timezone: "PST",
    timezoneNote: "Longevity science is Bay Area-led — Buck Institute, Stanford, Calico, Unity Biotech all PST. Post in PST morning to catch SF first, NYC at lunch",
    bestPostTimes: {
      Tuesday:   "9:00 AM PST",
      Wednesday: "8:30 AM PST",
      Thursday:  "9:30 AM PST",
      Friday:    "9:00 AM PST",
    },
    scheduleRationale: {
      Tuesday:   "9 AM PST = 12 PM EST — catches Bay Area longevity researchers mid-morning AND NYC oncology/biotech community at lunch simultaneously.",
      Wednesday: "8:30 AM PST is Senvi's prime slot. Longevity VC and biotech investors in SF check feeds early. EST audience is in their 11:30 AM pre-lunch window — highest mid-week engagement.",
      Thursday:  "9:30 AM PST = 12:30 PM EST. Senescent cell science is technical — Thu mid-morning PST hits the research community during their most focused reading window.",
      Friday:    "9 AM PST Friday catches aging-science community before the weekend. Longevity is a passion-driven field — Friday content gets strong weekend shares.",
    },
    audienceRegion: "U.S. West Coast — Bay Area longevity science cluster (Buck Institute, Stanford, Calico, Unity Biotech, SENS Research Foundation)",
    scheduleStrategy: "PST morning anchors Senvi in the Bay Area longevity community. Dual-timezone benefit: PST morning = EST lunch, maximising total audience reach in a single post.",
    audience: "Longevity researchers, oncologists, biotech investors, aging-science community, pharma partners, cancer recovery specialists",
    voice: "Precise, forward-looking, quietly confident. Sits at the intersection of longevity science and oncology — a rare and powerful position. Technically grounded without being jargony. The tone of a company solving something truly fundamental: why cells age, fail, and resist treatment. 'Making ineffective treatments effective' is the core message. Focused on what the body can do once the burden is removed.",
    badges: ["SenC peptide","Senescent cell clearance","Cancer therapy","Cancer recovery","Chronic disease","Increased healthspan","Provisional patent Nov 2024","First-in-class","Gorlin Immuno-Longevity"],
    pillars: [
      { day: "Tuesday", type: "Science insight", color: "#2BBFB3", example: "What are senescent cells? They stop dividing but stay metabolically active, releasing inflammatory signals that drive cancer, aging, and chronic disease. And until now, nothing could reliably remove them." },
      { day: "Wednesday", type: "Human story", color: "#0A2A28", example: "The scientist behind Senvi's SenC peptide: why they focused on senescence when everyone else chased different aging targets — and what the early data showed that made them certain." },
      { day: "Thursday", type: "Industry POV", color: "#2BBFB3", example: "Chemotherapy saves lives. It also accelerates biological aging by creating a surge of senescent cells the body can't clear. That burden is a problem medicine has barely begun to address." },
      { day: "Friday", type: "Proof & direction", color: "#1A8A84", example: "Complete tumour elimination in 7 days in combination. 70% reduction in senescent signal after one dose. >50% reduction in senescent cells in aged mice. Here is what SenC's early data actually shows." },
    ],
    postingDays: ["Tuesday","Wednesday","Thursday","Friday"],
  },
];

export type Company = (typeof companies)[0];
export type Pillar = (typeof companies)[0]["pillars"][0];
